// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickAndMixECommerce.Data;

#nullable disable

namespace PickAndMixECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240603164923_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PickAndMixECommerce.Models.Sweet", b =>
                {
                    b.Property<int>("SweetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SweetId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceInPence")
                        .HasColumnType("int");

                    b.Property<int>("StockInGrams")
                        .HasColumnType("int");

                    b.Property<string>("SweetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SweetId");

                    b.ToTable("Sweets");
                });
#pragma warning restore 612, 618
        }
    }
}
